---
- hosts: imageMe_nodes
  become: yes 
  tasks:
      - name: "install git"
        yum:
                name: git
                state: latest
      - name: "clone git"                
        git: 
                repo: https://github.com/jkanclerz/google-search-python.git
                version: master
                dest: /home/ec2-user/imageMe
      - name: "Set SEARCH_ENGINE"
        shell: "echo 'export SEARCH_ENGINE_ID=006879359584856769921:rplfy3clmho' >> .bashrc "
      - name: "Set GOOGLE_CLOUD_API"
        shell: "echo 'GOOGLE_CLOUD_API_KEY=AIzaSyDLLC1pqOxkWA8jUjM-Cfwbl_13Sh_2t98' >> .bashrc"
      - name: "creat directory"
        file:
                path: /home/ec2-user/bin
                state: directory
      - name: "copy file"
        copy:
                src: ./imageMe2.sh
                dest: /home/ec2-user/bin/imageMe.sh
                mode: +x
